services:
  - type: web
    name: fastapi-secure-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: SECRET_KEY
        value: cambia_esto_en_produccion